In [144]:
import numpy as np
import matplotlib.pyplot as plt
data = np.random.binomial(1, 0.25, (100000, 1000))
epsilon = 0.5

In [157]:
cummean = lambda x:  x.cumsum()/np.arange(1, len(x)+1)
means = np.abs(np.apply_along_axis(cummean, 1, data)-0.25)

In [158]:
pct = lambda x: np.where(x>=epsilon)[0].shape[0] / 100000

In [162]:
np.apply_along_axis(pct, 1,means)

array([0.e+00, 1.e-05, 0.e+00, ..., 0.e+00, 1.e-05, 0.e+00])

In [108]:
# column num 0
means[:, 0]

array([0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.75])

In [60]:
# row num 0
means[0,:]

array([0.25      , 0.25      , 0.25      , 0.25      , 0.05      ,
       0.08333333, 0.10714286, 0.        , 0.02777778, 0.05      ,
       0.06818182, 0.        , 0.05769231, 0.03571429, 0.01666667,
       0.0625    , 0.10294118, 0.08333333, 0.11842105, 0.1       ,
       0.08333333, 0.06818182, 0.05434783, 0.08333333, 0.11      ,
       0.09615385, 0.08333333, 0.10714286, 0.12931034, 0.11666667,
       0.13709677, 0.125     , 0.14393939, 0.13235294, 0.12142857,
       0.13888889, 0.12837838, 0.11842105, 0.10897436, 0.125     ,
       0.11585366, 0.10714286, 0.09883721, 0.11363636, 0.10555556,
       0.09782609, 0.11170213, 0.125     , 0.11734694, 0.13      ,
       0.14215686, 0.13461538, 0.12735849, 0.12037037, 0.11363636,
       0.10714286, 0.10087719, 0.11206897, 0.1059322 , 0.11666667,
       0.11065574, 0.10483871, 0.11507937, 0.109375  , 0.10384615,
       0.11363636, 0.12313433, 0.11764706, 0.11231884, 0.10714286,
       0.10211268, 0.09722222, 0.10616438, 0.10135135, 0.09666